-- INSERT INTO employer (
--         company_name,
--         company_address,
--         yearly_revenue,
--         is_hiring
--     ) VALUES(
--         'Learning Inc',
--         'Education street 12, London',
--         0.87,
--         TRUE
--     );
-- -- 
-- INSERT INTO employer (
--         company_name,
--         company_address,
--         yearly_revenue,
--         is_hiring
--     ) VALUES(
--         'Big Oli Inc',
--         'Slippery street 12, Huston',
--         112.55,
--         FALSE
--     );
-- -- 
-- INSERT INTO employer (
--         company_name,
--         company_address,
--         yearly_revenue,
--         is_hiring
--     ) VALUES(
--         'Hipster Food',
--         'Avocados street 5, Berlin',
--         6.17,
--         TRUE
--     );
-- 
-- 
INSERT INTO conversations (user_name, employer_name, message, date_sent)
VALUES ('Max Schewarz', 'Learning Inc', 'Hi, I like learning!', '2021-10-15 16:32:10');